from app import create_app
from models import db, User, Post, Reply

app = create_app()

def seed_database():
    with app.app_context():
        # 1. Create tables according to updated models
        db.create_all()

        # 2. Skip if users already exist
        if db.session.scalar(db.select(User)):
            print("Database already seeded!")
            return

        print("Seeding database with initial data...")

        # 3. Create test users with hashed passwords
        alice = User(username='alice', email='alice@example.com')
        alice.set_password('password123')

        bob = User(username='bob', email='bob@example.com')
        bob.set_password('password123')

        db.session.add_all([alice, bob])
        db.session.commit()

        # 4. Create an initial thread post
        first_post = Post(
            title='Welcome to the Discussion Board!',
            content='This post was generated by seed.py. Test the reply system by posting below!',
            user_id=alice.id
        )
        db.session.add(first_post)
        db.session.commit()

        # 5. Create a sample reply
        first_reply = Reply(
            content='Authentication and relationships are working great!',
            user_id=bob.id,
            post_id=first_post.id
        )
        db.session.add(first_reply)
        db.session.commit()

        print("Database seeded successfully!")
        print("\nTest User Credentials:")
        print("  1. Username: alice | Password: password123")
        print("  2. Username: bob   | Password: password123")

if __name__ == '__main__':
    seed_database()